HumanMobility/Models/BugReport.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HumanMobility.Models
{
    public class BugReport : Common.EntityBase
    {
        [Required]
        [ForeignKey("User")]
        public string UserId { get; set; }

        [Required]
        public DateTime Date { get; set; }

        [Required]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string Message { get; set; }

        public virtual ApplicationUser User { get; set; }
    }
}

HumanMobility/Models/Client-Side_ViewModels/BugReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HumanMobility.Models
{
    public class BugReportViewModel
    {
        [Required]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }
    }
}

HumanMobility/Controllers/BugReportController.cs
using System.Web.Mvc;
using HumanMobility.Models;
using HumanMobility.Models.Services;
using Microsoft.AspNet.Identity;
using PagedList;

namespace HumanMobility.Controllers
{
    [Authorize]
    public class BugReportController : Controller
    {
        #region Members
        private readonly IService _service;
        #endregion

        #region Constructor
        public BugReportController(IService service)
        {
            _service = service;
        }
        #endregion

        // GET: BugReport
        public ActionResult Index(int? page)
        {
            var reports = _service.GetBugReports(User);
            int pageNumber = page ?? 1;

            return View(reports.ToPagedList(pageNumber, 15));
        }

        // POST: BugReport
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(BugReportViewModel model)
        {
            if (!ModelState.IsValid || model == null)
                return View();

            _service.WriteBugReport(User.Identity.GetUserId(), model.Message);
            return RedirectToAction("Index");
        }
    }
}

HumanMobility/Views/Shared/BugReport.cshtml
@model HumanMobility.Models.BugReportViewModel
<div>
    @using (Html.BeginForm("Index", "BugReport", FormMethod.Post, new { @class = "form-horizontal col-md-12" }))
    {
        @Html.AntiForgeryToken()
        <br />
        <h3>Have a problem? Submit as a bug report!</h3>
        @Html.EditorFor(model => model.Message, new
{
    htmlAttributes = new
    {
        @class = "form-control",
        rows = "5",
        @style = "max-width: 6000px",
        @id = "bugReportEditor"
    }
})
        <span id="characters" style="float: right">299</span>
        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })

        <div class="form-group">
            <br />
            <div class="col-md-10">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        //resize: vertical ez kell
    }
</div>

HumanMobility/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/ico" href="~/Images/ic_launcher.png" />
    <title>@ViewBag.Title - HumanMobility</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Human Mobility", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Terms and Privacy", "Terms", "Home")</li>

                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Bug reports", "Index", "BugReport")</li>
                    }

                    @if (User.IsInRole("AdminRole"))
                    {
                        <li>@Html.ActionLink("Research", "Index", "Research")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Human Mobility</p>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/customHumanMobilityJs")
    @RenderSection("scripts", required: false)
</body>
</html>