HumanMobility/Models/ResearchViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using HumanMobility.Helpers;

namespace HumanMobility.Models
{
    public class ResearchViewModel
    {
        public DateTime From { get; set; } = DateTime.Today;

        public DateTime To { get; set; } = DateTime.Now;

        [Required]
        [Display(Name = "User")]
        public string UserName { get; set; }

        [Display(Name = "Export type")]
        public ExportType ExportType { get; set; } = ExportType.Database;

        public Fill Fill { get; set; } = Fill.LastData;
    }
}

HumanMobility/Models/SummaryViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HumanMobility.Models
{
    public class SummaryViewModel
    {
        [Required]
        [Display(Name = "From")]
        public DateTime FromDate { get; set; } = DateTime.Today;
    }
}

HumanMobility/Controllers/ResearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using DataAnalyzer.Entities;
using HumanMobility.DataAnalyzation;
using HumanMobility.Helpers;
using HumanMobility.Models;
using HumanMobility.Models.Services;
using Microsoft.AspNet.Identity;

namespace HumanMobility.Controllers
{
    [Authorize(Roles = Migrations.Configuration.AdminRole)]
    public class ResearchController : Controller
    {
        #region Members
        private readonly IService _service;
        #endregion

        #region Constructor
        public ResearchController(IService service)
        {
            _service = service;
        }
        #endregion

        #region Controller functions
        // GET: Research
        public ActionResult Index()
        {
            ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
            return View();
        }

        // POST: Research
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ResearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                return View();
            }
            ModelState.Clear();
            if (model.From > model.To)
            {
                ModelState.AddModelError("From", @"The first date must be less than second");
                ModelState.AddModelError("To", @"The first date must be less than second");
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                return View();
            }

            string exportedUserId = _service.GetUserId(model.UserName);
            string report = ReportHelper.GetData(model, _service, User.Identity.GetUserId(), exportedUserId);
            string fileName = string.Concat("Report-location-", model.UserName, "-", DateTime.Now, ".txt");

            return File(Encoding.UTF8.GetBytes(report), "text/plain", fileName);
        }

        // POST: Summary
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Summary(SummaryViewModel model)
        {
            if (!ModelState.IsValid || model == null)
            {
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                return View("Index");
            }

            ModelState.Clear();
            int days = Convert.ToInt32((DateTime.Today - model.FromDate).TotalDays);
            if (days < 0)
            {
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                ModelState.AddModelError("FromDate", @"The date can't be in the future.");
                return View("Index");
            }

            string summary = ReportHelper.GetSummary(_service, days, model.FromDate);
            string fileName = string.Concat("Summary-", DateTime.Now, ".txt");
            return File(Encoding.UTF8.GetBytes(summary), "text/plain", fileName);
        }

        public ActionResult Actigraphy(ResearchAccelerometerViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                return View("Index");
            }

            ModelState.Clear();
            if (model._From > model._To)
            {
                ModelState.AddModelError("_From", @"The first date must be less than second");
                ModelState.AddModelError("To", @"The first date must be less than second");
                ViewBag.Users = _service.GetUserNames().OrderBy(s => s);
                return View();
            }

            string fileName, report;
            string exportedUserId = _service.GetUserId(model._UserName);
            var activities = BulkCommands.GetActivities(exportedUserId, model._From, model._To);
            List<ActivityPerMinute> activityPerMinute = null;

            switch (model._ActivityOptions)
            {
                case AcceptableActivityOptions.Export:
                    model._ExportOptions = AcceptableExportOptions.Text;
                    fileName = "Report";
                    report = ReportHelper.GetAccelerometerData(activities);
                    break;

                case AcceptableActivityOptions.StandardDeviation:
                    model._ExportOptions = AcceptableExportOptions.Text;
                    fileName = "StdDev";
                    double devX = StandardDeviation.CalculateStdDev(activities.Select(m => (double) m.X).ToList());
                    double devY = StandardDeviation.CalculateStdDev(activities.Select(m => (double) m.Y).ToList());
                    double devZ = StandardDeviation.CalculateStdDev(activities.Select(m => (double) m.Z).ToList());
                    report = ReportHelper.ExportStdDev(devX, devY, devZ);
                    break;

                case AcceptableActivityOptions.EnergyExpenditure:
                case AcceptableActivityOptions.ZeroCrossing:
                    activityPerMinute = CalculateActivity.BeginAnalyzation(model._ActivityOptions, activities);
                    report = ReportHelper.ExportProcessedData(activityPerMinute);
                    fileName = string.Concat("Processed-", model._ActivityOptions);
                    break;

                default:
                    throw new ArgumentOutOfRangeException();
            }

            activities.Clear();
            GC.Collect();

            switch (model._ExportOptions)
            {
                case AcceptableExportOptions.Chart:
                    var chart = ReportHelper.CreateChart(activityPerMinute);

                    // ReSharper disable once PossibleNullReferenceException
                    activityPerMinute.Clear();
                    GC.Collect();

                    return File(chart.GetBytes(), "jpeg",
                        string.Concat(fileName, "-accelerometer - ", model._UserName, " - ", DateTime.Now, ".jpeg"));

                case AcceptableExportOptions.Text:
                    return File(Encoding.UTF8.GetBytes(report), "text/plain", 
                        string.Concat(fileName, "-accelerometer - ", model._UserName, " - ", DateTime.Now, ".txt"));

                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
        #endregion
    }
}

HumanMobility/Views/Research/Actigraphy.cshtml
@using HumanMobility.Helpers
@model HumanMobility.Models.ResearchAccelerometerViewModel

<h1>Accelerometer</h1>

@using (Html.BeginForm("Actigraphy", "Research", FormMethod.Post, new {@class = "form-horizontal col-md-12"}))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Customise the export</legend>

        @* _UserName *@
        <div class="form-group">
            @Html.LabelFor(m => m._UserName, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m._UserName, new SelectList(ViewBag.Users), "Select user", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model._UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        @* _From date *@
        <div class="form-group">
            @Html.LabelFor(m => m._From, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model._From, htmlAttributes: new {@id = "afromDatePicker", @class = "form-control", @placeholder = "07/25/2017"})
                @Html.ValidationMessageFor(model => model._From, "", new {@class = "text-danger"})
            </div>
        </div>

        @* To date *@
        <div class="form-group">
            @Html.LabelFor(m => m._To, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model._To, htmlAttributes: new { @id = "atoDatePicker", @class = "form-control", @placeholder = "08/25/2017" })
                @Html.ValidationMessageFor(model => model._To, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(m => m._ActivityOptions, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @foreach (var item in Enum.GetValues(typeof(DataAnalyzer.Entities.AcceptableActivityOptions)))
                {
                    <div class="row research-radiobuttons">
                        <label class="control-label">
                            @Html.RadioButtonFor(m => m._ActivityOptions, item, htmlAttributes: new { @checked = true })
                            @EnumDisplayStringHelper.GetDisplayStringFromName(item.ToString())
                        </label>
                    </div>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m._ExportOptions, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @foreach (var item in Enum.GetValues(typeof(DataAnalyzer.Entities.AcceptableExportOptions)))
                {
                    <div class="row research-radiobuttons">
                        <label class="control-label">
                            @Html.RadioButtonFor(m => m._ExportOptions, item, htmlAttributes: new { @checked = true })
                            @EnumDisplayStringHelper.GetDisplayStringFromName(item.ToString())
                        </label>
                    </div>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </fieldset>
}

HumanMobility/Views/Research/Index.cshtml
@{
    ViewBag.Title = "Research";
    @Styles.Render("~/Content/mainHM.css")
}

<div class="col-md-12">
    <div class="col-md-6">
        @Html.Partial("Search")

        @Html.Partial("Summary")
    </div>
    
    <div class="col-md-6">
        @Html.Partial("Actigraphy")
    </div>
</div>

HumanMobility/Views/Research/Search.cshtml
@using HumanMobility.Helpers
@model HumanMobility.Models.ResearchViewModel

<h1>Location</h1>

@using (Html.BeginForm("Index", "Research", FormMethod.Post, new { @class = "form-horizontal col-md-12" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Customise the export</legend>
        @* UserName *@
        <div class="form-group">
            @Html.LabelFor(m => m.UserName, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.UserName, new SelectList(ViewBag.Users), "Select user", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        @* From date *@
        <div class="form-group">
            @Html.LabelFor(m => m.From, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.From, htmlAttributes: new {@id = "fromDatePicker", @class = "form-control", @placeholder = "07/25/2017"})
                @Html.ValidationMessageFor(model => model.From, "", new {@class = "text-danger"})
            </div>
        </div>

        @* To date *@
        <div class="form-group">
            @Html.LabelFor(m => m.To, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.To, htmlAttributes: new { @id = "toDatePicker", @class = "form-control", @placeholder = "08/25/2017" })
                @Html.ValidationMessageFor(model => model.To, "", new { @class = "text-danger" })
            </div>
        </div>

        @* Export type *@
        <div class="form-group">
            @Html.LabelFor(m => m.ExportType, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @foreach (ExportType item in Enum.GetValues(typeof(ExportType)))
                {
                    <div class="row research-radiobuttons">
                        <label class="control-label">
                            @Html.RadioButtonFor(model => model.ExportType, item, htmlAttributes: new { @checked = true })
                            @EnumDisplayStringHelper.GetDisplayStringFromName(item.ToString())
                        </label>
                    </div>
                }
            </div>
        </div>

        @* Fill *@
        <div class="form-group">
            @Html.LabelFor(m => m.Fill, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @foreach (Fill item in Enum.GetValues(typeof(Fill)))
                {
                    <div class="row research-radiobuttons">
                        <label class="control-label">
                            @Html.RadioButtonFor(model => model.Fill, item, htmlAttributes: new { @checked = true })
                            @EnumDisplayStringHelper.GetDisplayStringFromName(item.ToString())
                        </label>
                    </div>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary">Submit</button>
                <button type="button" class="btn btn-default">Cancel</button>
            </div>
        </div>
    </fieldset>
}

HumanMobility/Views/Research/Summary.cshtml
@model HumanMobility.Models.SummaryViewModel

<h1>Location summary</h1>
@using (Html.BeginForm("Summary", "Research", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Summary creation can take a while.</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.FromDate, htmlAttributes: new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FromDate, htmlAttributes: new { @id = "summaryDatePicker", @class = "form-control", @placeholder = "07/25/2017" })
                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </fieldset>
}